# Generated by Django 5.2.4 on 2025-07-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_patient_admission_date_patient_bed_assigned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='assigned_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bed',
            name='assigned_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
